module.exports = {
  'after': require('./function/after'),
  'ary': require('./function/ary'),
  'before': require('./function/before'),
  'bind': require('./function/bind'),
  'bindKey': require('./function/bindKey'),
  'curry': require('./function/curry'),
  'curryRight': require('./function/curryRight'),
  'debounce': require('./function/debounce'),
  'defer': require('./function/defer'),
  'delay': require('./function/delay'),
  'flip': require('./function/flip'),
  'memoize': require('./function/memoize'),
  'negate': require('./function/negate'),
  'once': require('./function/once'),
  'overArgs': require('./function/overArgs'),
  'partial': require('./function/partial'),
  'partialRight': require('./function/partialRight'),
  'rearg': require('./function/rearg'),
  'rest': require('./function/rest'),
  'spread': require('./function/spread'),
  'throttle': require('./function/throttle'),
  'unary': require('./function/unary'),
  'wrap': require('./function/wrap')
};
