define(['./string/camelCase', './string/capitalize', './string/deburr', './string/endsWith', './string/escape', './string/escapeRegExp', './string/kebabCase', './string/lowerCase', './string/lowerFirst', './string/pad', './string/padEnd', './string/padStart', './string/parseInt', './string/repeat', './string/replace', './string/snakeCase', './string/split', './string/startCase', './string/startsWith', './string/template', './string/templateSettings', './string/toLower', './string/toUpper', './string/trim', './string/trimEnd', './string/trimStart', './string/truncate', './string/unescape', './string/upperCase', './string/upperFirst', './string/words'], function(camelCase, capitalize, deburr, endsWith, escape, escapeRegExp, kebabCase, lowerCase, lowerFirst, pad, padEnd, padStart, parseInt, repeat, replace, snakeCase, split, startCase, startsWith, template, templateSettings, toLower, toUpper, trim, trimEnd, trimStart, truncate, unescape, upperCase, upperFirst, words) {
  return {
    'camelCase': camelCase,
    'capitalize': capitalize,
    'deburr': deburr,
    'endsWith': endsWith,
    'escape': escape,
    'escapeRegExp': escapeRegExp,
    'kebabCase': kebabCase,
    'lowerCase': lowerCase,
    'lowerFirst': lowerFirst,
    'pad': pad,
    'padEnd': padEnd,
    'padStart': padStart,
    'parseInt': parseInt,
    'repeat': repeat,
    'replace': replace,
    'snakeCase': snakeCase,
    'split': split,
    'startCase': startCase,
    'startsWith': startsWith,
    'template': template,
    'templateSettings': templateSettings,
    'toLower': toLower,
    'toUpper': toUpper,
    'trim': trim,
    'trimEnd': trimEnd,
    'trimStart': trimStart,
    'truncate': truncate,
    'unescape': unescape,
    'upperCase': upperCase,
    'upperFirst': upperFirst,
    'words': words
  };
});
