define(['./utility/attempt', './utility/bindAll', './utility/cond', './utility/conforms', './utility/constant', './utility/flow', './utility/flowRight', './utility/identity', './utility/iteratee', './utility/matches', './utility/matchesProperty', './utility/method', './utility/methodOf', './utility/mixin', './utility/noop', './utility/nthArg', './utility/over', './utility/overEvery', './utility/overSome', './utility/property', './utility/propertyOf', './utility/range', './utility/rangeRight', './utility/times', './utility/toPath', './utility/uniqueId'], function(attempt, bindAll, cond, conforms, constant, flow, flowRight, identity, iteratee, matches, matchesProperty, method, methodOf, mixin, noop, nthArg, over, overEvery, overSome, property, propertyOf, range, rangeRight, times, toPath, uniqueId) {
  return {
    'attempt': attempt,
    'bindAll': bindAll,
    'cond': cond,
    'conforms': conforms,
    'constant': constant,
    'flow': flow,
    'flowRight': flowRight,
    'identity': identity,
    'iteratee': iteratee,
    'matches': matches,
    'matchesProperty': matchesProperty,
    'method': method,
    'methodOf': methodOf,
    'mixin': mixin,
    'noop': noop,
    'nthArg': nthArg,
    'over': over,
    'overEvery': overEvery,
    'overSome': overSome,
    'property': property,
    'propertyOf': propertyOf,
    'range': range,
    'rangeRight': rangeRight,
    'times': times,
    'toPath': toPath,
    'uniqueId': uniqueId
  };
});
